<a href="https://colab.research.google.com/github/priya3028/Workshop-on-Python-Programming-in-Data-Analytics-and-Machine-Learning/blob/master/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas Examples

Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8,10]) 
print(ds)


0     2
1     4
2     6
3     8
4    10
dtype: int64


Write a Pandas program to convert a Panda module Series to Python list and its type.

In [ ]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.


Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare the elements of the two Pandas Series.


Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a dictionary to a Pandas series.


Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [ ]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


Write a Pandas program to convert a NumPy array to a Pandas series.

Sample NumPy array: d1 = [10, 20, 30, 40, 50]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to change the data type of the given Series into numeric

['100', '200', 'python', '300.12', '400']

In [ ]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


Write a Pandas program to convert a given Series to an array

In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


**Write a Pandas program to sort a given Series.**

In [ ]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


**Write a Pandas program to add some data to an existing Series**

In [ ]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


**Write a Pandas program to create a subset of a given series based on value and condition.**

In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


**Write a Pandas program to change the order of index of a given series**.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


**Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series**.

In [ ]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


**Write a Pandas program to get the elements of an array values into column-wise**.

Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [14]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[24 14 21 12 13 19]


In [15]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.47961046 0.22767205 0.95437974]
  [0.01487638 0.46671001 0.12945164]
  [0.82382552 0.21588272 0.95705113]]

 [[0.29974125 0.29289932 0.6171375 ]
  [0.3604454  0.61216489 0.2054922 ]
  [0.58652769 0.56936745 0.64673271]]

 [[0.92615656 0.50328741 0.77065834]
  [0.62346344 0.45589784 0.07349502]
  [0.18381439 0.58894991 0.59993024]]]


In [16]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.99367174 0.04902604 0.7013279  0.41636552 0.96123336]
 [0.69840629 0.7385223  0.30001566 0.74585484 0.02153211]
 [0.87023971 0.73804038 0.53522146 0.39887814 0.82220323]
 [0.98473879 0.79709911 0.48603195 0.41572808 0.9222777 ]
 [0.69279125 0.51111549 0.96757848 0.81719057 0.16152537]]
Minimum and Maximum Values:
0.021532111281860056 0.9936717432889027


In [17]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.84536961 0.99614875 0.22491311 0.61710978]
 [0.25486603 0.66273205 0.9682719  0.8384958 ]
 [0.9166823  0.20652382 0.59056648 0.01022046]
 [0.52015642 0.35170961 0.24923188 0.33543059]
 [0.2635326  0.77197433 0.16702359 0.89878467]
 [0.61923536 0.03400417 0.4972583  0.69121121]
 [0.77086747 0.59254368 0.21632502 0.64733808]
 [0.64917672 0.61192888 0.72540028 0.58386925]
 [0.10431675 0.15334046 0.22398733 0.60748358]
 [0.71216044 0.11956146 0.67936076 0.63893016]]
First 5 rows of the above array:
[[0.84536961 0.99614875 0.22491311 0.61710978]
 [0.25486603 0.66273205 0.9682719  0.8384958 ]
 [0.9166823  0.20652382 0.59056648 0.01022046]
 [0.52015642 0.35170961 0.24923188 0.33543059]
 [0.2635326  0.77197433 0.16702359 0.89878467]]
First 3 columns of the above array:
[[0.84536961 0.99614875 0.22491311 0.61710978]
 [0.25486603 0.66273205 0.9682719  0.8384958 ]
 [0.9166823  0.20652382 0.59056648 0.01022046]
 [0.52015642 0.35170961 0.24923188 0.33543059]
 [0.2635326  0.7719

In [18]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[2 5 9 6 0 8 7 4 3 1]
Same result using permutation():
[8 4 7 6 9 0 2 1 3 5]


In [19]:
import numpy as np
x = np.arange(10)
np.random.randint(x,100)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[5 1 3 7 4 0 8 9 6 2]
[0 1 2 3 4 5 6 7 8 9]
