<a href="https://colab.research.google.com/github/priya3028/Workshop-on-Python-Programming-in-Data-Analytics-and-Machine-Learning/blob/master/Day_3_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


In [2]:
import pandas as pd
l=([i for i in range(1000,20000) if i%5==0])
ds = pd.Series(l) 
print(ds)

0        1000
1        1005
2        1010
3        1015
4        1020
        ...  
3795    19975
3796    19980
3797    19985
3798    19990
3799    19995
Length: 3800, dtype: int64


In [3]:
import pandas as pd
l1=([i for i in range(0,101) if i%2==0])
ds1 = pd.Series(l1)
l2=([i for i in range(0,100) if i%2!=0])
ds2 = pd.Series(l2)
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0       1.0
1       5.0
2       9.0
3      13.0
4      17.0
5      21.0
6      25.0
7      29.0
8      33.0
9      37.0
10     41.0
11     45.0
12     49.0
13     53.0
14     57.0
15     61.0
16     65.0
17     69.0
18     73.0
19     77.0
20     81.0
21     85.0
22     89.0
23     93.0
24     97.0
25    101.0
26    105.0
27    109.0
28    113.0
29    117.0
30    121.0
31    125.0
32    129.0
33    133.0
34    137.0
35    141.0
36    145.0
37    149.0
38    153.0
39    157.0
40    161.0
41    165.0
42    169.0
43    173.0
44    177.0
45    181.0
46    185.0
47    189.0
48    193.0
49    197.0
50      NaN
dtype: float64
Subtract two Series:
0    -1.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5    -1.0
6    -1.0
7    -1.0
8    -1.0
9    -1.0
10   -1.0
11   -1.0
12   -1.0
13   -1.0
14   -1.0
15   -1.0
16   -1.0
17   -1.0
18   -1.0
19   -1.0
20   -1.0
21   -1.0
22   -1.0
23   -1.0
24   -1.0
25   -1.0
26   -1.0
27   -1.0
28   -1.0
29   -1.0
30   -1.0
31   -1.0
32   -1.0
33   -

In [4]:
import pandas as pd
l1=([i for i in range(0,1000) if i%7==0])
d1 = pd.Series(l1)
l2=([i for i in range(0,1000) if i%11==0])
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   True
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87   

In [5]:
import numpy as np
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
np_array = np.array(l1)
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000]
Converted Pandas series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


In [6]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [7]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


In [8]:
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
s = pd.Series(l1)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=7
new_s = s[s%n==0]
print(new_s)
n=5
new_s = s[s%n==0]
print(new_s)

Original Data Series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64

Subset of the above Data Series:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


In [9]:
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


In [11]:
import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)

[[0.81537967 0.80373583 0.13627728 0.23166346]
 [0.622967   0.29120753 0.10185904 0.95509739]
 [0.27733389 0.48499406 0.86249988 0.2084603 ]
 [0.62945124 0.74832383 0.85940289 0.30491804]]
2nd and 3rd rows of the above array:
[[0.622967   0.29120753 0.10185904 0.95509739]
 [0.27733389 0.48499406 0.86249988 0.2084603 ]]


In [12]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.28686234 0.05830407 0.71342797 0.26144421 0.94515823 0.4232473
  0.5921017  0.0310793  0.31689819 0.32186709]
 [0.60048894 0.1210489  0.61218648 0.95137112 0.95795702 0.13475793
  0.89568931 0.95098808 0.61669159 0.48031264]
 [0.21009974 0.94928515 0.20650595 0.73224972 0.86815386 0.56788206
  0.45090759 0.85740661 0.06288906 0.86663277]
 [0.80795311 0.16947798 0.81904674 0.88222647 0.30075349 0.75351229
  0.23652793 0.90082545 0.07777605 0.41151458]
 [0.34979548 0.82636555 0.00348135 0.75119118 0.04720377 0.80477481
  0.37416724 0.72198638 0.09483052 0.43498044]
 [0.00512363 0.20734745 0.58218154 0.03830064 0.98583491 0.76272157
  0.77440451 0.28289515 0.44298279 0.37349982]
 [0.92591086 0.65488772 0.53771052 0.3472688  0.16282829 0.81298316
  0.12914608 0.12033811 0.23512903 0.54611466]
 [0.08447392 0.80433279 0.86098491 0.73329015 0.29869678 0.4100023
  0.90372043 0.30822664 0.29092729 0.3260632 ]
 [0.24406419 0.06314924 0.06452873 0.01875908 0.92987484 0.9323720

In [13]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[266 118 178 264 216 187 198 156]


In [14]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[11  7 17 12  1  5 15  4 16  3  6 14 10  8  9 18 19  2  0 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
